In [2]:
import pandas as pd

In [3]:
url = "https://raw.githubusercontent.com/Biranavan-P/black-jack/main/resource/blkjckhands.csv"

In [4]:
df = pd.read_csv(url)

In [5]:
df

,Unnamed: 0,PlayerNo,card1,card2,card3,card4,card5,sumofcards,dealcard1,dealcard2,...,dealcard4,dealcard5,sumofdeal,blkjck,winloss,plybustbeat,dlbustbeat,plwinamt,dlwinamt,ply2cardsum
0,0,Player1,7,10,0,0,0,17,10,8,...,0,0,18,nowin,Loss,Beat,Dlwin,0,10,17
1,1,Player2,10,9,0,0,0,19,10,8,...,0,0,18,nowin,Win,Plwin,Beat,20,0,19
2,2,Player3,9,8,0,0,0,17,10,8,...,0,0,18,nowin,Loss,Beat,Dlwin,0,10,17
3,3,Player4,2,10,0,5,0,17,10,8,...,0,0,18,nowin,Loss,Beat,Dlwin,0,10,12
4,4,Player5,10,2,0,5,0,17,10,8,...,0,0,18,nowin,Loss,Beat,Dlwin,0,10,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
899995,1,Player2,10,7,0,0,0,17,3,9,...,2,0,18,nowin,Loss,Beat,Dlwin,0,10,17
899996,2,Player3,6,1,10,0,0,17,3,9,...,2,0,18,nowin,Loss,Beat,Dlwin,0,10,7
899997,3,Player4,4,2,9,0,0,15,3,9,...,2,0,18,nowin,Loss,Beat,Dlwin,0,10,6
899998,4,Player5,9,10,0,0,0,19,3,9,...,2,0,18,nowin,Win,Plwin,Beat,20,0,19
899999,5,Player6,5,10,0,0,0,15,3,9,...,2,0,18,nowin,Loss,Beat,Dlwin,0,10,15

In [6]:
df.isnull().sum()

Unnamed: 0     0
PlayerNo       0
card1          0
card2          0
card3          0
card4          0
card5          0
sumofcards     0
dealcard1      0
dealcard2      0
dealcard3      0
dealcard4      0
dealcard5      0
sumofdeal      0
blkjck         0
winloss        0
plybustbeat    0
dlbustbeat     0
plwinamt       0
dlwinamt       0
ply2cardsum    0
dtype: int64

In [7]:
df.dtypes

Unnamed: 0      int64
PlayerNo       object
card1           int64
card2           int64
card3           int64
card4           int64
card5           int64
sumofcards      int64
dealcard1       int64
dealcard2       int64
dealcard3       int64
dealcard4       int64
dealcard5       int64
sumofdeal       int64
blkjck         object
winloss        object
plybustbeat    object
dlbustbeat     object
plwinamt        int64
dlwinamt        int64
ply2cardsum     int64
dtype: object

In [8]:
df.columns

Index(['Unnamed: 0', 'PlayerNo', 'card1', 'card2', 'card3', 'card4', 'card5',
       'sumofcards', 'dealcard1', 'dealcard2', 'dealcard3', 'dealcard4',
       'dealcard5', 'sumofdeal', 'blkjck', 'winloss', 'plybustbeat',
       'dlbustbeat', 'plwinamt', 'dlwinamt', 'ply2cardsum'],
      dtype='object')

In [9]:
df = df.drop("plwinamt",axis = 1)
df = df.drop("dlwinamt" ,axis = 1)
df = df.drop("Unnamed: 0",axis = 1)
df = df.drop("PlayerNo",axis = 1)
df

,card1,card2,card3,card4,card5,sumofcards,dealcard1,dealcard2,dealcard3,dealcard4,dealcard5,sumofdeal,blkjck,winloss,plybustbeat,dlbustbeat,ply2cardsum
0,7,10,0,0,0,17,10,8,0,0,0,18,nowin,Loss,Beat,Dlwin,17
1,10,9,0,0,0,19,10,8,0,0,0,18,nowin,Win,Plwin,Beat,19
2,9,8,0,0,0,17,10,8,0,0,0,18,nowin,Loss,Beat,Dlwin,17
3,2,10,0,5,0,17,10,8,0,0,0,18,nowin,Loss,Beat,Dlwin,12
4,10,2,0,5,0,17,10,8,0,0,0,18,nowin,Loss,Beat,Dlwin,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
899995,10,7,0,0,0,17,3,9,4,2,0,18,nowin,Loss,Beat,Dlwin,17
899996,6,1,10,0,0,17,3,9,4,2,0,18,nowin,Loss,Beat,Dlwin,7
899997,4,2,9,0,0,15,3,9,4,2,0,18,nowin,Loss,Beat,Dlwin,6
899998,9,10,0,0,0,19,3,9,4,2,0,18,nowin,Win,Plwin,Beat,19
899999,5,10,0,0,0,15,3,9,4,2,0,18,nowin,Loss,Beat,Dlwin,15

In [ ]:
df.to_csv("cleaned.csv",index=True)